CREATE TABLE IF NOT EXISTS `TOKENS`
(
    `ID`              VARCHAR(42)  NOT NULL,
    `USER_ID`         VARCHAR(41)  NOT NULL,
    `SESSION_ID`      VARCHAR(255) NOT NULL,
    `TYPE`            VARCHAR(16)  NOT NULL,
    `TOKEN`           TEXT         NOT NULL,
    `STATE`           VARCHAR(16)  NOT NULL,
    `EXPIRES_AT`      DATETIME     NOT NULL,
    `ETAG`            VARCHAR(255) NOT NULL DEFAULT '1',
    `CREATED_AT`      DATETIME     NOT NULL DEFAULT NOW(),
    `LAST_UPDATED_AT` DATETIME,

    CONSTRAINT `TOKENS_PK` PRIMARY KEY (`ID`),
    CONSTRAINT `TOKENS_CK_ID` CHECK (`ID` LIKE 'TOKEN.%' AND CHAR_LENGTH(`ID`) = 42),
    CONSTRAINT `TOKENS_CK_USER_ID` CHECK (`USER_ID` LIKE 'USER.%' AND CHAR_LENGTH(`USER_ID`) = 41),
    CONSTRAINT `TOKENS_CK_TYPE` CHECK (`TYPE` IN ('ACCESS_TOKEN', 'REFRESH_TOKEN')),
    CONSTRAINT `TOKENS_CK_STATE` CHECK (`STATE` IN ('ACTIVE', 'EXPIRED', 'REVOKED')),
    CONSTRAINT `TOKENS_CK_CREATED_AT` CHECK (`CREATED_AT` >= NOW()),
    CONSTRAINT `TOKENS_CK_LAST_UPDATED_AT` CHECK (`LAST_UPDATED_AT` >= `CREATED_AT` AND `LAST_UPDATED_AT` >= NOW())
);