CREATE TABLE IF NOT EXISTS `CONTACTS`
(
    `ID`              VARCHAR(44)  NOT NULL,
    `USER_ID`         VARCHAR(41)  NOT NULL,
    `TYPE`            VARCHAR(16)  NOT NULL,
    `VALUE`           VARCHAR(255) NOT NULL,
    `IS_PRIMARY`      BOOLEAN      NOT NULL DEFAULT FALSE,
    `ETAG`            VARCHAR(255) NOT NULL DEFAULT '1',
    `CREATED_AT`      DATETIME     NOT NULL DEFAULT NOW(),
    `LAST_UPDATED_AT` DATETIME,

    CONSTRAINT `CONTACTS_PK` PRIMARY KEY (`ID`),
    CONSTRAINT `CONTACTS_UQ_SINGLE_PRIMARY_CONTACT_PER_TYPE_PER_USER_ID` UNIQUE (`USER_ID`, `TYPE`, `IS_PRIMARY`),
    CONSTRAINT `CONTACTS_CK_ID` CHECK (`ID` LIKE 'CONTACT.%' AND CHAR_LENGTH(`ID`) = 44),
    CONSTRAINT `CONTACTS_CK_USER_ID` CHECK (`USER_ID` LIKE 'USER.%' AND CHAR_LENGTH(`USER_ID`) = 41),
    CONSTRAINT `CONTACTS_CK_TYPE` CHECK (`TYPE` IN ('EMAIL')),
    CONSTRAINT `CONTACTS_CK_CREATED_AT` CHECK (`CREATED_AT` >= NOW()),
    CONSTRAINT `CONTACTS_CK_LAST_UPDATED_AT` CHECK (`LAST_UPDATED_AT` >= `CREATED_AT` AND `LAST_UPDATED_AT` >= NOW())
);