CREATE TABLE IF NOT EXISTS `USERS`
(
    `ID`              VARCHAR(41)  NOT NULL,
    `USERNAME`        VARCHAR(32)  NOT NULL,
    `PASSPHRASE`      VARCHAR(255) NOT NULL,
    `TYPE`            VARCHAR(16),
    `STATE`           VARCHAR(8),
    `ETAG`            VARCHAR(255) NOT NULL DEFAULT '1',
    `CREATED_AT`      DATETIME     NOT NULL DEFAULT NOW(),
    `LAST_UPDATED_AT` DATETIME,

    CONSTRAINT `USERS_PK` PRIMARY KEY (`ID`),
    CONSTRAINT `USERS_UQ_USERNAME` UNIQUE (`USERNAME`),
    CONSTRAINT `USERS_CK_ID` CHECK (`ID` LIKE 'USER.%' AND CHAR_LENGTH(`ID`) = 41),
    CONSTRAINT `USERS_CK_USERNAME` CHECK (CHAR_LENGTH(`USERNAME`) > 1),
    CONSTRAINT `USERS_CK_TYPE` CHECK (`TYPE` IN ('USER', 'PRIVILEGED_USER')),
    CONSTRAINT `USERS_CK_STATE` CHECK (`STATE` IN ('ACTIVE', 'INACTIVE', 'BLOCKED')),
    CONSTRAINT `USERS_CK_CREATED_AT` CHECK (`CREATED_AT` >= NOW()),
    CONSTRAINT `USERS_CK_LAST_UPDATED_AT` CHECK (`LAST_UPDATED_AT` >= `CREATED_AT` AND `LAST_UPDATED_AT` >= NOW())
);