server:
  port: ${SERVICE.SETTINGS.PORT:10100}
spring:
  application:
    name: nyxx-access-management-service
  datasource:
    url: jdbc:mysql://${SERVICE.SETTINGS.DATASOURCE.HOST:127.0.0.1}:${SERVICE.SETTINGS.DATASOURCE.PORT:3306}/${SERVICE.SETTINGS.DATASOURCE.DATABASE:ACCESS_MANAGEMENT_SERVICE_DATABASE}?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SERVICE.SETTINGS.DATASOURCE.USER:ACCESS_MANAGEMENT_SERVICE_DATABASE_USER}
    password: ${SERVICE.SETTINGS.DATASOURCE.PASSPHRASE}
  flyway:
    locations: classpath:database/migrations
    table: SCHEMA_HISTORY
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
logging:
  level:
    com:
      nerosec:
        nyxx: ${SERVICE.SETTINGS.LOGGING.LEVEL:INFO}